### ISSUE TITLE
Why do I use your HRNetW18, the forward time is 2.5 times as long as resnet50

### ISSUE THREAD

**Issue by devilztt** [HRNet/HRNet-Image-Classification#3]
Why do I use your HRNetW18, the forward time is 2.5 times as long as resnet50

**Comment by sunke123** [comment]
@devilztt 
Hi, thanks for your attention.
GFLOPs doesn't correspond to the runtime because of different implementation.
In Pytorch implementation, the convolutional layers are executed in series, even though we connect the different branches in parallel. So, the speed of HRNets are actually slower than ResNets, which is similar to Group Convolution vs Standard Convolution. 
Training and inference speed for our HRNet could be improved if Pytorch supports the parallel convolutions.

**Comment by devilztt** [comment]
@sunke123 
Thank you for your reply.  I will close this issues.

**Comment by mehtadushy** [comment]
Hi @devilztt @sunke123 

Have you tried timing the forward pass by tracing the model with torchscript (jit) first ?
